### ISSUE TITLE
Doesn't decode key

### ISSUE THREAD

**Issue by elidoran** [kristoferk/query-to-obj#1]
For example, try parsing `'bl%40h=blah'` and it doesn't decode the key.

```javascript
console.log(require('query-to-obj')('bl%40h=blah', {decode:true}))
// 'bl%40h=blah'
// should be: 'bl@h=blah
```

I tried altering [your decode test](https://github.com/kristoferk/query-to-obj/blob/master/spec/query-to-obj.spec.js#L5) by putting an encoded character into the key and it fails.

**Comment by kristoferk** [comment]
Released a patch (version 1.0.2) to [npm](https://www.npmjs.com/package/query-to-obj) and bower to fix this is issue.
It should now decode the key as well:
https://runkit.com/kristoferk/5a876d5f21466b00130a78ca
